# Generated by Django 4.2.3 on 2023-07-21 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldo',
            name='cheque_esp',
        ),
        migrations.AddField(
            model_name='cartao_credito',
            name='limite',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cheque_esp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_cheque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('juros', models.DecimalField(decimal_places=1, max_digits=10)),
                ('banco', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
