# Generated by Django 4.2.3 on 2023-07-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_remove_saldo_cheque_esp_cartao_credito_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='cheque_esp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.cheque_esp'),
            preserve_default=False,
        ),
    ]
