# Generated by Django 4.2.3 on 2023-07-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_saldo_cheque_esp'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_paga',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
