# Generated by Django 4.2.3 on 2023-07-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_despesa_data_paga'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='changed',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=50),
            preserve_default=False,
        ),
    ]
