# Generated by Django 4.2.3 on 2023-08-01 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_despesa_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='cartao_credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.cartao_credito'),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='cheque_esp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.cheque_esp'),
        ),
    ]
