# Generated by Django 4.2.3 on 2023-08-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_alter_saldo_cartao_credito_alter_saldo_cheque_esp'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='dp_rc',
            field=models.CharField(choices=[('Despesa', 'Despesa'), ('Receita', 'Receita')], default='Despesa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='dp_rc',
            field=models.CharField(choices=[('Despesa', 'Despesa'), ('Receita', 'Receita')], default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
