# Generated by Django 4.2.3 on 2023-09-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0009_compras_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(null=True),
        ),
    ]
